config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'

  root 'static_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def opensource
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button> <a class="navbar-brand" href="#">Brand</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Opensource at WolfieReader', opensource_path %>
      </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" />
      </div>
      <button type="submit" class="btn btn-default">
        Submit
      </button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="#">Link</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
        <ul class="dropdown-menu">
          <li>
            <a href="#">Action</a>
          </li>
          <li>
            <a href="#">Another action</a>
          </li>
          <li>
            <a href="#">Something else here</a>
          </li>
          <li class="divider">
          </li>
          <li>
            <a href="#">Separated link</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WolfieReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to WolfieReader</h1>
  <p>Since they shut down Google Reader we're going to bring it back like the party never left and with more features. Well, maybe.</p>


  <p><%= link_to 'About', about_path, class: "btn btn-primary btn-lg" %></p>
</div>

app/views/static_pages/opensource.html.erb
<%
    gems = [{name: 'rails', version: '4.2.2'},
            {name: 'bootstrap-sass', version: '3.2.0.0'},
            {name: 'sass-rails', version: '5.0.2'},
            {name: 'uglifier', version: '2.5.3'},
            {name: 'coffee-rails', version: '4.1.0'},
            {name: 'jquery-rails', version: '4.0.3'},
            {name: 'turbolinks', version: '2.3.0'},
            {name: 'jbuilder', version: '2.2.3'},
            {name: 'sdoc', version: '0.4.0' },
            {name: 'sqlite3', version: '1.3.9'},
            {name: 'byebug', version: '3.4.0'},
            {name: 'web-console', version: '2.0.0.beta3'},
            {name: 'spring', version: '1.1.3'},
            {name: 'minitest-reporters', version: '1.0.5'},
            {name: 'mini_backtrace', version: '0.1.3'},
            {name: 'guard-minitest', version: '2.3.1'},
            {name: 'pg', version: '0.17.1'},
            {name: 'rails_12factor', version: '0.0.2'}]
%>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
    <% gems.each do |gem| %>
      <tr>
        <td><%= gem[:name] %></td>
        <td><%= gem[:version] %></td>
      </tr>
    <% end %>
  </tbody>
</table>